# This is firat tutorial on numpy


In [1]:
import numpy as np   #import numpy
from numpy import pi # import pi
from numpy import random


#1  arrays

In [2]:
a = np.arange(9).reshape(3,3)  # np.arange(n-1).rehsape(row,col)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
b = np.arange(9,18).reshape(3,3)
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [4]:
 a * b   # element multiplication  

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [5]:
 a @ b   # matris or dot multiplication or a.dot(b)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [6]:
 x = np.array([[2+3j,3+10j], [6-4j,8+1j]], dtype=complex)   # dtype =  int, float, complex
 x

array([[2. +3.j, 3.+10.j],
       [6. -4.j, 8. +1.j]])

In [7]:
x.shape #to know the shape 
x.size  #to know the size (dtype/4)
x.dtype # to know the data type 
x.ndim  # tknow the dimansion 

2

In [8]:
np.zeros((3,4)) # to create null matrix(m,n)
np.ones((4,4))  # to create ones matrix(m,n)
np.diag([1,2,3]) # to create matrix with diagonal (1,2,3)
np.eye(3)        # to create uity matrix
np.empty((2,3))   # to create matrix with rendom values np.empty((2,3))  

array([[1.136e-321, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [9]:
np.arange(15,30 +1,5)  # np.arange(from,to,gap)
np.arange(15,30 +1,5).reshape(2,2) # to reshape the matrix


array([[15, 20],
       [25, 30]])

In [10]:
np.linspace(8,9,10) # np.linspace(from,to,no of partation)

array([8.        , 8.11111111, 8.22222222, 8.33333333, 8.44444444,
       8.55555556, 8.66666667, 8.77777778, 8.88888889, 9.        ])

In [11]:
 x = np.linspace(0,2*pi,20)
 f = np.sin(x)
 f

array([ 0.00000000e+00,  3.24699469e-01,  6.14212713e-01,  8.37166478e-01,
        9.69400266e-01,  9.96584493e-01,  9.15773327e-01,  7.35723911e-01,
        4.75947393e-01,  1.64594590e-01, -1.64594590e-01, -4.75947393e-01,
       -7.35723911e-01, -9.15773327e-01, -9.96584493e-01, -9.69400266e-01,
       -8.37166478e-01, -6.14212713e-01, -3.24699469e-01, -2.44929360e-16])

In [12]:
f.mean() # mean 0f all values 
f.max()   # max of all valus 
f.min()   # min of all values 

-0.9965844930066698

In [13]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a.sum(axis=1) # axis=0 row # axis= 1 col 
a.sort(axis=0) # to arange in sort
a.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [15]:
np.square(a) # squre of matrix
np.sqrt(a)   #sqrt of matrix
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])